# AIM : To implement Recurrent Neural Network for sentiment analysis

**Name : Trideep Nandi**

**Class : CS4**

**Batch: 2**

**Enrollment : 0827CS211248**

###  Demonstration of RNN Architecure

Recurrent Neural Networks (RNNs) are a type of artificial neural network designed to recognize patterns in sequences of data, such as text, genomes, handwriting, or the spoken word. Here are some key points about RNNs:

1. **Sequence Processing:** RNNs are used for input sequences, output sequences, or both. They can process data of variable length, unlike other neural networks which require fixed length inputs and outputs.

2. **Memory:** RNNs have "memory" in the form of hidden states that capture information about what has been calculated so far. This is particularly useful when the current output depends on the previous inputs.

3. **Backpropagation Through Time:** RNNs learn to map inputs to outputs through a variant of backpropagation called backpropagation through time (BPTT).

4. **Vanishing and Exploding Gradients:** RNNs can suffer from vanishing and exploding gradient problems, making them hard to train for long sequences.

5. **Gated Cells:** To overcome the issues with traditional RNNs, variants such as Long Short-Term Memory (LSTM) and Gated Recurrent Units (GRU) have been developed. These variants have gating mechanisms that control the flow of information to and from the memory cell.

RNNs are used in a variety of applications including:

- **Natural Language Processing (NLP):** RNNs are used for language modeling, machine translation, text generation, and sentiment analysis.

- **Speech Recognition:** RNNs can be used to convert spoken language into written form.

- **Time Series Prediction:** RNNs can predict future values of a time series like stock prices or weather patterns.

- **Music Composition:** RNNs can generate music by learning patterns in musical sequences.

- **Gesture Recognition:** RNNs can recognize patterns in sequences of movements for gesture-based control systems.

The code below imports the Sequential model class from Keras, which is used to create a linear stack of layers, and the Dense and SimpleRNN layer classes, which are used to create fully connected and simple recurrent layers respectively.

In [2]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

The code below creates a Sequential model in Keras with a Simple Recurrent Neural Network (RNN) layer having 3 neurons and an input shape of (4,5), followed by a Dense output layer with 1 neuron and a sigmoid activation function.

In [3]:
model=Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))


The model.summary() code prints a summary representation of your model, showing the layer types, output shapes, and the number of parameters, both trainable and non-trainable.

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


This output shows the summary of the Sequential model, indicating it has two layers - a SimpleRNN layer with 3 neurons (27 parameters) and a Dense layer with 1 neuron (4 parameters), totaling to 31 trainable parameters and no non-trainable parameters.

The code below prints the shape of the weight matrix of the first layer in the model (SimpleRNN layer) and then returns the actual weight values of that layer.

In [5]:
print(model.get_weights()[0].shape)
model.get_weights()[0]


(5, 3)


array([[ 0.48222476,  0.3212604 ,  0.09172821],
       [-0.07115531, -0.6588487 , -0.72447187],
       [ 0.75353223, -0.23280686,  0.8544466 ],
       [-0.51625884, -0.43121096,  0.6041532 ],
       [-0.13687783, -0.00232309,  0.7819211 ]], dtype=float32)

The code below prints the shape of the recurrent weight matrix of the first layer in the model (SimpleRNN layer) and then returns the actual recurrent weight values of that layer.

In [6]:
print(model.get_weights()[1].shape)
model.get_weights()[1]


(3, 3)


array([[ 0.47776914,  0.5143387 , -0.7121744 ],
       [-0.875431  ,  0.21120954, -0.43475407],
       [-0.07319281,  0.8311717 ,  0.55117744]], dtype=float32)

The code below prints the shape of the bias vector of the first layer in the model (SimpleRNN layer) and then returns the actual bias values of that layer.

In [7]:
print(model.get_weights()[2].shape)
model.get_weights()[2]


(3,)


array([0., 0., 0.], dtype=float32)

The code below prints the shape of the weight matrix of the second layer in the model (Dense layer) and then returns the actual weight values of that layer.

In [8]:
print(model.get_weights()[3].shape)
model.get_weights()[3]


(3, 1)


array([[1.046249 ],
       [1.1538934],
       [0.7615069]], dtype=float32)

The code below prints the shape of the bias vector of the second layer in the model (Dense layer) and then returns the actual bias values of that layer.

In [9]:
print(model.get_weights()[4].shape)
model.get_weights()[4]


(1,)


array([0.], dtype=float32)

### Integer Encoding

Integer encoding is a method of converting categorical data, specifically text data, into numerical form so that it can be used by a machine learning algorithm. In integer encoding, each unique word is represented by a unique integer. For example, in a list of words ['apple', 'banana', 'apple', 'cherry'], the integer encoded form could be [1, 2, 1, 3]. This method is often used in natural language processing tasks.

In [10]:
import numpy as np

The below line of code is creating a list named `docs` in Python. The list contains 10 strings, each of which appears to be a phrase or sentence. This list could be used for various purposes, such as text processing, natural language processing, or other forms of analysis.

In [11]:
docs = ['go india',
'india india',
'hip hip hurray',
'jeetega bhai jeetega india jeetega',
'bharat mata ki jai',
'kohli kohli',
'sachin sachin',
'dhoni dhoni',
'modi ji ki jai',
'inquilab zindabad']


The below code creates a Keras Tokenizer object with a specified out-of-vocabulary token, fits it on the provided documents, displays the word index, word counts, and document count, then converts the documents into sequences of integers representing the words based on the fitted tokenizer.

In [12]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')
tokenizer.fit_on_texts(docs)
tokenizer.word_index
tokenizer.word_counts
tokenizer.document_count
sequences = tokenizer.texts_to_sequences(docs)
sequences


[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

This code uses Keras's `pad_sequences` function to pad the sequences of integers representing the words to the same length by adding zeros at the end of each sequence (post-padding).

In [13]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)